"""Generate the paper-style case atlas from graph enumeration and saved evidence.

No search is run. Labels distinguish analytic exclusion, solver-checked
exclusion, and OPEN. These are extremal-obstruction cases, not valuation points.
"""
import argparse,json
from collections import Counter
from itertools import combinations_with_replacement
from pathlib import Path
from structural_reductions import PROFILES,PERMUTATIONS,PAIRS,graph_data,canonical_edges,catalog

ROOT=Path(__file__).resolve().parent
LINKS={
    'T1': 'RESEARCH_STATUS.md#t1', 'T5':'RESEARCH_STATUS.md#t5',
    'T6':'RESEARCH_STATUS.md#t6', 'T7':'RESEARCH_STATUS.md#t7',
    'T9':'RESEARCH_STATUS.md#t9', 'CP1':'RESEARCH_STATUS.md#cp1',
    'CP2':'RESEARCH_STATUS.md#cp2',
}


def classify():
    directory=ROOT/'experiment-results/two-source'
    recorded=json.loads((directory/'all-compensation.json').read_text())
    compensation={r['case']['id'] for r in recorded if r['status']=='unsat'}
    finite_menus={'2223_003','2223_011','2223_013'}
    replay=json.loads((directory/'cvc5-replay.json').read_text())
    verified={Path(r['file']).stem for r in replay if r['replies']==['unsat'] and r['check_proofs']}
    assert len(compensation)==50
    assert all(case+'-compensation' in verified for case in compensation)
    assert all(case+'-pareto' in verified for case in finite_menus)
    dags=[x for code in range(4096) if (x:=graph_data(code)) is not None]
    rows=[]
    for profile in PROFILES:
        group=[p for p in PERMUTATIONS if all(profile[i]==profile[p[i]] for i in range(4))]
        patterns=sorted({canonical_edges(e,group) for e,_,_ in dags})
        for edges in patterns:
            code=sum(1<<PAIRS.index(e) for e in edges)
            _,sources,reach=graph_data(code)
            case_id=''.join(map(str,profile))+'_'+format(code,'03x')
            if len(sources)==1:status='T5'
            elif any(profile[k]==1 for k in sources):status='T6'
            elif any(not any(profile[i]!=2 and not reach[k][i] for i in range(4))
                     for k in sources if profile[k]==2):status='T7'
            elif len(sources)==4:status='T9'
            elif case_id in compensation:status='CP1'
            elif case_id in finite_menus:status='CP2'
            else:status='OPEN'
            rows.append({'id':case_id,'profile':list(profile),'edges':[list(e) for e in edges],
                         'sources':list(sources),'status':status,
                         'evidence':LINKS.get(status)})
    prior={c['id'] for c in catalog()[0]}
    assert {r['id'] for r in rows if r['status'] in {'T9','CP1','CP2','OPEN'}}==prior
    expected=set(json.loads((directory/'reduction-summary.json').read_text())['remaining_ids'])
    assert {r['id'] for r in rows if r['status']=='OPEN'}==expected
    return rows


def label(status,prefix=''):
    return '**OPEN**' if status=='OPEN' else f'[{status}]({prefix}{LINKS[status]})'


def render():
    rows=classify();files={};counts=Counter(r['status'] for r in rows)
    summary={'scope':'Necessary extremal EFR-obstruction templates; not universal Mode C',
             'acyclic_nonempty_templates':len(rows),'status_counts':dict(sorted(counts.items())),
             'open_by_sources':dict(sorted(Counter(len(r['sources']) for r in rows if r['status']=='OPEN').items())),
             'cases':rows}
    files['research/case-status.json']=json.dumps(summary,separators=(',',':'))+'\n'
    top=['# Case atlas: theorems, checked propositions, and open cases','',
         'Generated by `python case_status.py`; no solver search is run. Read [RESEARCH_STATUS.md](RESEARCH_STATUS.md) for definitions and theorem statements.','',
         '**Meaning of a closed cell:** this configuration cannot be a terminal extremal obstruction to EFR existence. It does not mean every predecessor in the cell admits immediate insertion.','',
         '`T` = human proof (T4 uses the cited restoration theorem). `CP` = computer-checked proposition with an explicit encoding trust boundary. `OPEN` = unresolved continuous region. Counts count graph templates, not valuations.','',
         'Agents are 0,1,2,3. An edge i → j means i envies j. Only simultaneous relabelings preserving the bundle-size profile are identified. The omitted good is canonically 9.','',
         '## All 18 starting size profiles','',
         '| Profile | Status | Open terminal templates |','| --- | --- | ---: |']
    for p in combinations_with_replacement(range(10),4):
        if sum(p)!=9:continue
        profile=','.join(map(str,p));key=''.join(map(str,p))
        if 0 in p:status=label('T1');n=0
        else:
            part=[r for r in rows if r['profile']==list(p)];c=Counter(r['status'] for r in part);n=c['OPEN']
            status='; '.join(f'{label(k)} × {c[k]}' for k in ['T5','T6','T7','T9','CP1','CP2','OPEN'] if c[k])
            profile=f'[{profile}](research/cases/{key}.md)'
        top.append(f'| ({profile}) | {status} | {n} |')
    top+=['','Strict envy cycles are removed by [T2](RESEARCH_STATUS.md#t2), before the acyclic catalog below.','',
          '## Size profile × number of sources','',
          'Mixed cells list every theorem/proposition used and the number still OPEN. The individual graph rows are linked from the profile.','',
          '| Profile | One source | Two sources | Three sources | Four sources |','| --- | --- | --- | --- | --- |']
    for p in PROFILES:
        key=''.join(map(str,p));part=[r for r in rows if r['profile']==list(p)]
        cells=[]
        for n in range(1,5):
            c=Counter(r['status'] for r in part if len(r['sources'])==n)
            cells.append('; '.join(f'{label(k)} × {c[k]}' for k in ['T5','T6','T7','T9','CP1','CP2','OPEN'] if c[k]) or 'No template')
        top.append('| ['+','.join(map(str,p))+f'](research/cases/{key}.md) | '+' | '.join(cells)+' |')
        lines=[f'# Individual cases: ({",".join(map(str,p))})','',
               '[Atlas](../../CASE_ATLAS.md) · [Theorem register](../../RESEARCH_STATUS.md#theorem-register)','',
               'Each row is one canonical acyclic envy graph. Closure means exclusion as an extremal obstruction, not automatic insertion at every starting allocation.','',
               '| Case ID | Envy edges | Sources | Answer |','| --- | --- | --- | --- |']
        for r in part:
            edges=', '.join(f'{a}→{b}' for a,b in r['edges']) or 'None'
            lines.append(f'| `{r["id"]}` | {edges} | '+', '.join(map(str,r['sources']))+' | '+label(r['status'],'../../')+' |')
        files[f'research/cases/{key}.md']='\n'.join(lines)+'\n'
    top+=['','## Count audit','',f'- Acyclic nonempty templates: {len(rows)}.',
          f'- Human-proof exclusions: {sum(v for k,v in counts.items() if k.startswith("T"))}.',
          f'- Additional computer-checked exclusions: {counts["CP1"]+counts["CP2"]}.',
          f'- OPEN: {counts["OPEN"]} (94 two-source, 9 three-source).','',
          'The 50 compensation solver closures include the four-source case, which is assigned T9 here because it also has a human proof. Hence CP1 labels 49 rows; CP2 labels 3. No row is counted twice.','',
          'The earlier 156-case catalog is retained as a historical baseline. The original 220 valuation-ranking roots are a different decomposition and are not classified by this table.','',
          '[All open cases](research/OPEN_CASES.md) · [Machine-readable ledger](research/case-status.json) · [Theoretical next steps](RESEARCH_STATUS.md#roadmap)']
    files['CASE_ATLAS.md']='\n'.join(top)+'\n'
    open_rows=[r for r in rows if r['status']=='OPEN']
    lines=['# Open cases requiring examination','',
           'These 103 templates remain open for the extremal EFR-existence route. No entry asserts failure of Mode C or EFR. See the [roadmap](../RESEARCH_STATUS.md#roadmap).','',
           '## First target: nine three-source cases','',
           '| ID | Bundle sizes | Envy edges | Status |','| --- | --- | --- | --- |']
    for r in open_rows:
        if len(r['sources'])==3:lines.append(f'| `{r["id"]}` | {r["profile"]} | '+', '.join(f'{a}→{b}' for a,b in r['edges'])+' | **OPEN** |')
    lines+=['','## Full open-case ledger','',
            '| ID | Bundle sizes | Envy edges | Sources | Status |','| --- | --- | --- | --- | --- |']
    for r in open_rows:lines.append(f'| `{r["id"]}` | {r["profile"]} | '+(', '.join(f'{a}→{b}' for a,b in r['edges']) or 'None')+' | '+', '.join(map(str,r['sources']))+' | **OPEN** |')
    files['research/OPEN_CASES.md']='\n'.join(lines)+'\n'
    return files


if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
    for name,content in render().items():
        target=ROOT/name
        if a.check:
            if not target.exists() or target.read_text()!=content:raise SystemExit('Stale generated case table: '+name)
        else:target.parent.mkdir(parents=True,exist_ok=True);target.write_text(content)
    print('Case atlas verified.' if a.check else 'Case atlas generated.')
